title: Hassaan Ahmed
description: Personal website of Hassaan Ahmed

# Use remote_theme instead of theme
remote_theme: jekyll/minima

plugins:
  - jekyll-remote-theme

# Navigation menu
header_pages:
  - index.md
  - about.md
  - read.md
