title: Hassaan Ahmed
description: Personal website of Hassaan Ahmed

# Fetch the theme directly from GitHub
remote_theme: jekyll/minima

plugins:
  - jekyll-remote-theme

# Navigation menu
header_pages:
  - index.md
  - about.md
  - read.md
